"use client"

import { useState } from "react"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Card, CardContent, CardHeader, CardTitle, CardFooter } from "@/components/ui/card"
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"
import { MOCK_CLIENTS, MOCK_ORG } from "@/lib/mock-data"
import { Plus, Trash2, Wand2, ArrowLeft, Send, Scale, Loader2, FileText } from "lucide-react"
import Link from "next/link"
import { suggestInvoiceLineItemDescriptions } from "@/ai/flows/invoice-line-item-description-suggester"
import { draftStrategicAgreement } from "@/ai/flows/contract-drafter"
import { useToast } from "@/hooks/use-toast"
import { useRouter } from "next/navigation"
import { Separator } from "@/components/ui/separator"
import { Textarea } from "@/components/ui/textarea"

export default function NewInvoicePage() {
  const router = useRouter()
  const { toast } = useToast()
  const [loading, setLoading] = useState(false)
  const [loadingContract, setLoadingContract] = useState(false)
  const [items, setItems] = useState([{ id: '1', description: '', quantity: 1, price: 0 }])
  const [selectedClient, setSelectedClient] = useState('')
  const [taxRate, setTaxRate] = useState(0)
  const [dueDate, setDueDate] = useState('')
  const [contractContent, setContractContent] = useState('')

  const addItem = () => {
    setItems([...items, { id: Math.random().toString(), description: '', quantity: 1, price: 0 }])
  }

  const removeItem = (id: string) => {
    setItems(items.filter(i => i.id !== id))
  }

  const updateItem = (id: string, field: string, value: any) => {
    setItems(items.map(i => i.id === id ? { ...i, [field]: value } : i))
  }

  const handleAiSuggest = async (itemId: string, currentDesc: string) => {
    if (!currentDesc) {
      toast({ title: "Error", description: "Please enter a brief description first." })
      return
    }
    
    setLoading(true)
    try {
      const result = await suggestInvoiceLineItemDescriptions({ briefDescription: currentDesc })
      if (result.suggestions && result.suggestions.length > 0) {
        updateItem(itemId, 'description', result.suggestions[0])
        toast({ title: "AI Suggestion Applied", description: "Professional description updated." })
      }
    } catch (error) {
      toast({ title: "AI Error", description: "Could not fetch suggestions." })
    } finally {
      setLoading(false)
    }
  }

  const handleGenerateContract = async () => {
    const client = MOCK_CLIENTS.find(c => c.id === selectedClient)
    if (!client) {
      toast({ title: "Error", description: "Please select a client first." })
      return
    }

    const serviceBrief = items.map(i => i.description).filter(Boolean).join(", ")
    if (!serviceBrief) {
      toast({ title: "Error", description: "Add at least one item description." })
      return
    }

    setLoadingContract(true)
    try {
      const result = await draftStrategicAgreement({
        businessName: MOCK_ORG.name,
        clientName: client.name,
        serviceBrief: serviceBrief,
        brandingTone: MOCK_ORG.brandColor ? "Professional and Value-First" : "Modern Corporate"
      })
      setContractContent(result.contractBody)
      toast({ title: "Agreement Drafted", description: "Outcome contract generated by ClearBill AI." })
    } catch (error) {
      toast({ title: "AI Error", description: "Could not draft agreement." })
    } finally {
      setLoadingContract(false)
    }
  }

  const subtotal = items.reduce((sum, i) => sum + (i.quantity * i.price), 0)
  const tax = (subtotal * taxRate) / 100
  const total = subtotal + tax

  const handleCreate = () => {
    setLoading(true)
    // Simulate API call
    setTimeout(() => {
      setLoading(false)
      toast({ title: "Invoice Created", description: "A unique payment link and outcome agreement have been generated." })
      router.push('/dashboard/invoices')
    }, 1500)
  }

  return (
    <div className="max-w-4xl mx-auto space-y-6 pb-20">
      <div className="flex items-center gap-4">
        <Button variant="ghost" size="icon" asChild>
          <Link href="/dashboard/invoices">
            <ArrowLeft className="size-4" />
          </Link>
        </Button>
        <h1 className="text-3xl font-bold">New Invoice</h1>
      </div>

      <div className="grid gap-6 md:grid-cols-3">
        <div className="md:col-span-2 space-y-6">
          <Card>
            <CardHeader>
              <CardTitle>Invoice Details</CardTitle>
            </CardHeader>
            <CardContent className="space-y-6">
              <div className="grid gap-4 sm:grid-cols-2">
                <div className="space-y-2">
                  <Label>Client</Label>
                  <Select value={selectedClient} onValueChange={setSelectedClient}>
                    <SelectTrigger className="h-11 rounded-xl">
                      <SelectValue placeholder="Select a client" />
                    </SelectTrigger>
                    <SelectContent>
                      {MOCK_CLIENTS.map(client => (
                        <SelectItem key={client.id} value={client.id}>{client.name}</SelectItem>
                      ))}
                    </SelectContent>
                  </Select>
                </div>
                <div className="space-y-2">
                  <Label>Due Date</Label>
                  <Input type="date" className="h-11 rounded-xl" value={dueDate} onChange={e => setDueDate(e.target.value)} />
                </div>
              </div>

              <div className="space-y-4">
                <Label className="text-xs uppercase tracking-widest text-muted-foreground font-black">Line Items</Label>
                {items.map((item, index) => (
                  <div key={item.id} className="grid gap-3 items-end sm:grid-cols-12 border-b pb-4">
                    <div className="sm:col-span-6 space-y-1.5">
                      <Label className="text-[10px] uppercase font-bold text-muted-foreground">Description</Label>
                      <div className="relative">
                        <Input 
                          placeholder="Highlight the value provided..." 
                          className="h-11 rounded-xl pr-10"
                          value={item.description}
                          onChange={e => updateItem(item.id, 'description', e.target.value)}
                        />
                        <Button 
                          size="icon" 
                          variant="ghost" 
                          className="absolute right-1 top-1 h-9 w-9 text-accent hover:text-accent"
                          onClick={() => handleAiSuggest(item.id, item.description)}
                          disabled={loading}
                        >
                          <Wand2 className="size-4" />
                        </Button>
                      </div>
                    </div>
                    <div className="sm:col-span-2 space-y-1.5">
                      <Label className="text-[10px] uppercase font-bold text-muted-foreground">Qty</Label>
                      <Input 
                        type="number" 
                        className="h-11 rounded-xl"
                        value={item.quantity}
                        onChange={e => updateItem(item.id, 'quantity', parseFloat(e.target.value))}
                      />
                    </div>
                    <div className="sm:col-span-3 space-y-1.5">
                      <Label className="text-[10px] uppercase font-bold text-muted-foreground">Price</Label>
                      <Input 
                        type="number" 
                        className="h-11 rounded-xl font-bold"
                        value={item.price}
                        onChange={e => updateItem(item.id, 'price', parseFloat(e.target.value))}
                      />
                    </div>
                    <div className="sm:col-span-1">
                      <Button 
                        variant="ghost" 
                        size="icon" 
                        className="text-destructive size-11"
                        onClick={() => removeItem(item.id)}
                        disabled={items.length === 1}
                      >
                        <Trash2 className="size-4" />
                      </Button>
                    </div>
                  </div>
                ))}
                <Button variant="outline" size="sm" onClick={addItem} className="w-full border-dashed rounded-xl h-11">
                  <Plus className="size-4 mr-2" /> Add Strategic Win Item
                </Button>
              </div>
            </CardContent>
          </Card>

          <Card className="border-accent/20 bg-accent/5">
            <CardHeader className="flex flex-row items-center justify-between">
              <div>
                <CardTitle className="text-lg flex items-center gap-2">
                  <Scale className="size-5 text-accent" /> Strategic Outcome Agreement
                </CardTitle>
                <p className="text-xs text-muted-foreground mt-1">Protect your work and command market rates with an AI-drafted contract.</p>
              </div>
              <Button 
                variant="outline" 
                size="sm" 
                className="border-accent text-accent hover:bg-accent/10"
                onClick={handleGenerateContract}
                disabled={loadingContract}
              >
                {loadingContract ? <Loader2 className="size-3 animate-spin mr-2" /> : <Wand2 className="size-3 mr-2" />}
                {contractContent ? "Refine Agreement" : "Draft Agreement"}
              </Button>
            </CardHeader>
            <CardContent>
              <Textarea 
                placeholder="The agreement will appear here... Use ClearBill AI to highlight your value." 
                className="min-h-[200px] rounded-xl bg-white/50 border-accent/10 text-sm leading-relaxed"
                value={contractContent}
                onChange={(e) => setContractContent(e.target.value)}
              />
            </CardContent>
          </Card>
        </div>

        <div className="space-y-6">
          <Card className="shadow-lg border-none">
            <CardHeader>
              <CardTitle>Summary</CardTitle>
            </CardHeader>
            <CardContent className="space-y-4">
              <div className="flex justify-between text-sm">
                <span className="text-muted-foreground">Subtotal</span>
                <span>${subtotal.toLocaleString(undefined, { minimumFractionDigits: 2 })}</span>
              </div>
              <div className="space-y-2">
                <Label className="text-xs">Tax Rate (%)</Label>
                <Input 
                  type="number" 
                  className="h-10 rounded-lg"
                  value={taxRate} 
                  onChange={e => setTaxRate(parseFloat(e.target.value) || 0)} 
                />
              </div>
              <div className="flex justify-between text-sm">
                <span className="text-muted-foreground">Tax</span>
                <span>${tax.toLocaleString(undefined, { minimumFractionDigits: 2 })}</span>
              </div>
              <Separator />
              <div className="flex justify-between font-bold text-lg">
                <span>Total</span>
                <span className="text-accent">${total.toLocaleString(undefined, { minimumFractionDigits: 2 })}</span>
              </div>
            </CardContent>
            <CardFooter>
              <Button className="w-full h-14 bg-accent hover:bg-accent/90 rounded-xl text-lg shadow-lg shadow-accent/20" onClick={handleCreate} disabled={loading}>
                {loading ? "Architecting Portal..." : "Create & Send Link"}
                {!loading && <Send className="size-4 ml-2" />}
              </Button>
            </CardFooter>
          </Card>

          <div className="p-4 bg-slate-900 text-white rounded-2xl space-y-3">
             <div className="flex items-center gap-2">
               <ShieldCheck className="size-4 text-accent" />
               <span className="text-[10px] font-black uppercase tracking-widest">Market Value Safeguard</span>
             </div>
             <p className="text-[10px] text-slate-400 leading-relaxed italic">
               "By attaching a Strategic Agreement, you are framing this invoice not as a request for payment, but as the fulfillment of a professional outcome."
             </p>
          </div>
        </div>
      </div>
    </div>
  )
}
